#!/usr/local/bin/zsh
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Stephen Johnson <stevej@ucla.edu>
#

SCRIPT_NAME=$(echo "$0" | sed 's/^-\(.*\)/shell-\1" ".zshrc/' | xargs basename)
if [ "$DEBUG" != "" ] || [ -f .DEBUG ]; then echo "$(date): sourcing $SCRIPT_NAME..."; fi


# Load bash profiles
if [ -f ~/.bash_profile ] && [ -r ~/.bash_profile ]; then source ~/.bash_profile; fi



# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...



# Override settings from zprezto
unsetopt correct
unsetopt noclobber
export LESS='-g -i -M -R -S -w -z-4'

# History file overrides
export HISTFILE=~/.zsh_history
export HISTSIZE=40000
export SAVEHIST=40000
if [[ $HISTFILESIZE -gt $HISTSIZE ]]; then
    export SAVEHIST=$HISTFILESIZE
    export HISTSIZE=$HISTFILESIZE
fi




# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

# Enable online help
unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# Test if iTerm2 shell integration is enabled
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


### Init rbenv
#if [ "$DEBUG" != "" -o -f .DEBUG ]; then echo "rbenv: $(which rbenv)"; fi
export RBENV_ROOT=/usr/local/var/rbenv
eval "$(rbenv init -)" 

### Init perlbrew
# eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
source ~/perl5/perlbrew/etc/bashrc

# Alias for working with plex and Deluge torrent downloader
alias pms='/Applications/Plex\ Media\ Server.app/Contents/MacOS/Plex\ Media\ Scanner'


# GOPATH for 'go get' 
# https://golang.org/doc/code.html#GOPATH
export GOPATH="$HOME/.gopath"
export PATH="$PATH:$GOPATH/bin"


########################################################################
######### Don't modify this section or place anything after it #########
########################################################################

# Turn off startup profiling
if [[ "$PROFILE_STARTUP" == true ]]; then
    unsetopt xtrace
    exec 2>&3 3>&-
fi

SCRIPT_NAME=$(echo "$0" | sed 's/^-\(.*\)/shell-\1" ".zshrc/' | xargs basename)
if [ "$DEBUG" != "" ] || [ -f .DEBUG ]; then echo "$(date): done sourcing $SCRIPT_NAME..."; fi

########################################################################
########################################################################
